name = "website"
main = ".svelte-kit/cloudflare/_worker.js"
preview_urls = false
workers_dev = false
compatibility_date = "2025-11-08"
compatibility_flags = [
	"nodejs_compat"
]

[assets]
binding = "ASSETS"
directory = ".svelte-kit/cloudflare"

[observability]
enabled = false

[build]
command = "yarn run build"

[vars]
NODE_VERSION = "22.21.1"

[[routes]]
pattern = "about.killbasa.com"
custom_domain = true
